### ISSUE TITLE
Sort by Extention

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#11]
Sort by (filename) Extension,

Should be just 2 files `OpenEditorsMainView` and `EditorComparator`. Isn't it so?

**Comment by dbickley** [comment]
Yes, it should be pretty simple.

**Comment by achimmihca** [comment]
Done. You can now define a sequence of sort types instead a single sort type.
For example, you can define a sort sequence (fileextension, filename, filepath).
Editing is done via Drag and Drop of the sort sequence in a new dialog.
