### ISSUE TITLE
[feature request] Sync mode, or activate Editor when list item is activated 

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#14]
Sync mode, or activate Editor when list item is activated

**Comment by dbickley** [comment]
Not sure I understand exactly what you mean by this.

**Comment by paulvi** [comment]
a new mode, when activated:  
When user clicks once on a list item, the corresponding file Editor goes to top.


in current (default mode),  
user needs to double click to bring up that file Editor.

**Comment by achimmihca** [comment]
Not sure if I understand correctly. Do you want to open files with a single click instead double click?
If so, then this is a duplicate of #20
