### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#17]
It is currently not clear how to build (or some files are missing)

See #2 for adding README

**Comment by dbickley** [comment]
To do a full build and push it out to the an update site is a pain, I have two other projects that manage that. To do a local build you will need the PDE tools (which might already be part of your eclipse).

Open the MANIFEST.MF 

To install to local click "Export Wizard" -> Select "Instal to localhost" radio -> click the "Finish Button"

To test in a different version of eclipse you can click the Run/Debug icon on the upper right side.

If you are still having issues please let me know and I can help debug.

<img width="930" alt="screen shot 2018-05-08 at 1 02 00 pm" src="https://user-images.githubusercontent.com/586039/39780850-77bb78e6-52c2-11e8-8648-77399eb36193.png">

**Comment by dbickley** [comment]
I also pushed some files on my local that had changed, Hopefully that helps.

**Comment by paulvi** [comment]
That is for manual build.

Eclipse has also build with maven (using tycho plugins https://www.eclipse.org/tycho/)

The structure of project should be like https://github.com/Mathieuu/CsvEdit
i.e. plugin in its folder, feature in its folder. Folder names are usually like ids.

See https://github.com/open-archetypes/tycho-eclipse-plugin-archetype

**Comment by dbickley** [comment]
I will look into that.

**Comment by achimmihca** [comment]
Done. Documentation is updated.
I had a look at it and found Tycho and Maven to be way over the top for this little plugin.
