### ISSUE TITLE
Can't Create New Project with Open Editors Installed

### ISSUE THREAD

**Issue by kferrone** [dbickley/OpenEditors#19]
For whatever reason I get a unhandled event loop exception from org.eclipse.swt.ui when I create a new project when `OpenEditors` is installed. I uninstall this plugin and everything works fine. 

Env:
Eclipse Photon
MacOS
Java9

Maybe it's another plugin conflicting, who knows. Here are some I use a lot just in case they don't play nice. 

Webclipse
DBeaver
TraceCompass
Ruby Tools
Docker Tools

Keep up the good work, this is a pretty sweet plugin so far.

**Comment by tretum** [comment]
This is apparently an issue with Eclipse, where this plugin only increases/shows the symptoms of the bug:
Other discussion about the wizard issue: https://github.com/eclipse/xtext-eclipse/issues/1143
Ticket in Eclipse bug tracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=549409
