### ISSUE TITLE
Please change View icon

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#3]
Currently it is some human

![image](https://user-images.githubusercontent.com/1614482/39352134-5c44531a-4a36-11e8-8fab-708893dbff4f.png)

**Comment by paulvi** [comment]
For example to use icon of new untitled Editor (as above)

or e.g. http://www.iconarchive.com/search?q=editor

**Comment by dbickley** [comment]
Yeah, I am not a fan of the icon, but I got tired of looking for a better one. (I am normally a backend developer, UI is not my strong point). 

I will have a look at the link you sent and see if I can find a better one.

**Comment by paulvi** [comment]
Try also https://marketplace.eclipse.org/content/eclipaint Icon Manager

![](https://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/screenshot_2.jpg?itok=4juyaJWA)

**Comment by achimmihca** [comment]
I suggest to look at some open source icon collections. No need to create something yourself.

For instance, there are the Material Design Icons: https://material.io/tools/icons/?style=baseline
Linux desktop environments (KDE, Gnome, ...) also provide their icons as open source (e.g. Oxygen, Breeze, ...). For instance, here are the ones for Oxygen: https://github.com/KDE/oxygen-icons5/tree/master/16x16/places

**Comment by achimmihca** [comment]
Even better: Eclipse has an integrated Plug-in Image Browser: [see here](https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Fviews%2Fimage_browser_view.htm).
For simplicity and consistency with the Eclipse UI, I would just use an icon that already exists, e.g. from the Project Explorer or plain file.

**Comment by achimmihca** [comment]
Done. I re-used a simple text file icon of Eclipse and stacked it three times. It makes for a fitting item for open editors I think.
