### ISSUE TITLE
Request: Add feature to switch naming to "pretty Name"

### ISSUE THREAD

**Issue by openPhiL** [dbickley/OpenEditors#35]
Hi. Great Idea, this Plugin for Eclipse. I tend to have too much open, too :) 

I develop in "ABAP", which has ugly and unimportant filenames and somewhat of a pretty-version of that. 
My request for feature is to give an option to customize what your editor-overview displays in the naming. 
Here is a picture: 
![image](https://user-images.githubusercontent.com/43743230/227465673-fd0557fa-53a3-4def-8fbb-d9ded59a4383.png)

The simplest way would be to have a switch for the user to switch vom "show filename" (as it seems to be done currently) to "switch to tab-name", to show the same thing that is displayed in the tab. 

Have a good day!
PhiL

**Comment by dbickley** [comment]
Hey Phil. That seems like a valid feature. However I am not currently maintaining this project, way to busy at my current job and other side projects. However if you (or anyone else that sees this) puts in a pull request I would be happy to review it and try and remember how to do a release. 😁

**Comment by openPhiL** [comment]
Thanks for the reply. Good to know you are there, technically speaking. I might give it a try :)

**Comment by dbickley** [comment]
If you do give it a shot and have any questions/get stuck let me know, I am happy try and help.
