### ISSUE TITLE
Option to switch list to table

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#4]
Sometime it is more convenient to see name and path.

On the other hand, Eclipse built-in "Switch to Editor" dialog already show so

![image](https://user-images.githubusercontent.com/1614482/39352424-3c433a9e-4a37-11e8-8c89-bb8dc9f79b54.png)

Maybe this plugin can have icon to open eclipse "Switch to Editor" dialog,
then showing View with list as table (with several column) can be said "already implemented"

![image](https://user-images.githubusercontent.com/1614482/39352308-e5ab4ca8-4a36-11e8-818b-510e4fa0e5f8.png)

**Comment by achimmihca** [comment]
Interesting. Maybe it would make sense to build the Open Editors view on this? Not sure though.

**Comment by achimmihca** [comment]
There is a new feature that shows the path of the files with the same name. Furthermore, a tooltip now shows the full path of a file. So I don't think this is needed anymore.

Anyhow, I added a toolbar button that opens the "Switch to Editor" dialog of Eclipse.
