### ISSUE TITLE
 update feature id on https://marketplace.eclipse.org/content/open-editors  

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#5]
Possibly https://marketplace.eclipse.org/content/open-editors marketplace entry has wrong feature id, as this plugin cannot be installed by drag-n-drop of Eclipse icon onto toolbar.

Eclipse showed error "Cannot find ..." and continued thinking long time.

Only by using update site `http://deepnoodle.com/update/`

**Comment by dbickley** [comment]
After playing around with config files for while I finally got it to work by adding in a category.xml. Let me know if you continue to have issues.
