### ISSUE TITLE
[question] What is "Pin" command?

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#6]
What is "Pin" command?

Pinned Editor item still disappears, when the Editor is closed.

**Comment by achimmihca** [comment]
The current behavior is as follows:
"Pin" will move the editor to the top of the list. This is all.
Further, a pinned editor can still be closed and then when re-opened it will not be pinned anymore.

Do you request another behavior or can this issue be closed?

**Comment by achimmihca** [comment]
If you wish for a different behavior, please open a new issue. This question has been answered for now and I will close it.
