### ISSUE TITLE
[Question] What is "Show in" command and how to use it?

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#9]
What is "Show in" command and how to use it?

![image](https://user-images.githubusercontent.com/1614482/39354587-6c6eb6b6-4a3d-11e8-989a-f0ae674dd7ba.png)

**Comment by dbickley** [comment]
I am unsure exactly what it does, it looks like something eclipse adds by default. In the keys preferences if I search for "show in" it appears like all "views" have an option for it.

**Comment by paulvi** [comment]
Eclipse context menu has "Show In" submenu.

**Comment by achimmihca** [comment]
related to #8

**Comment by achimmihca** [comment]
So, "Show In" is a context menu option for files and editors to send them to a specific view. For instance, you can open a Java file in the Java Editor or the Plain Text Editor via these commands.
However, for the OpenEditors plugin it is irrelevant.
